title: Apache-JMeter
description: Learn Apache JMeter by doing
template:
  repo: apache-jmeter-template
  name: apache-jmeter
  description: Learn JMeter by doing
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Validate your environment
    description: Install the prerequisites
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: 01-Closed.md
        issue: 1
      - type: createIssue
        title: Upload your first JMeter test plan
        body: 01-ThreadGroup.md
  - title: Upload your first JMeter test plan
    description: Upload your first JMeter test plan
    link: '{{ repoUrl }}/issues/2'
    event: push
    actions:
      - type: respond
        issue: 2
        with: 02-Closed.md      
      - type: getFileContents
        filename: 01-ThreadGroup.jmx
      - type: gate
        left: hello123
        right: hello
        operator: ===
        else:
        - type: respond
          with: Please upload valid JMX
      - type: createIssue
        body: 03-Assertions.md
        title: New issue
  - title: Assertions
    event: issues.closed
    description: Learn Assertions
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: 03-Assertions.md