title: Fun with JMeter
description: Learn Apache JMeter by doing
template:
  repo: apache-jmeter-template
  name: apache-jmeter
  description: Learn JMeter by doing
before:
  - type: createIssue
    title: Welcome!
    body: 01-Welcome.md
steps:
  - title: Validate your environment
    description: Install and validate the prerequisites
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: 01-Closed.md
        issue: 1
      - type: createIssue
        title: Upload your first JMeter test plan
        body: 01-ThreadGroup.md
  - title: Upload your first JMeter test plan
    description: Upload your first JMeter test plan
    link: '{{ repoUrl }}/issues/2'
    event: push
    actions:
      - type: respond
        issue: 2
        with: 02-Closed.md      
      - type: createIssue
        body: 02-HTTPSampler.md
        title: Add HTTP Sampler
  - title: HTTP Sampler
    event: push
    description: Adding a HTTP Sampler
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        issue: 3
        with: 03-Closed.md
      - type: createIssue
        body: 03-Listener.md
        title: Add a Listener
  - title: Listeners
    event: push
    description: Adding a Listener
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: respond
        issue: 4
        with: 04-Closed.md
      - type: createIssue
        body: 05-CSVDataSetConfig.md
        title: Data Parameterization
  - title: Data Parameterization
    event: push
    description: Implement data parameterization
    link: '{{ repoUrl }}/issues/5'
    actions:
      - type: respond
        issue: 5
        with: 05-Closed.md
      - type: createIssue
        body: 06-Timers.md
        title: Timers      